# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  engine: wiredTiger
  wiredTiger:
    engineConfig:
      cacheSizeGB: 32

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1,172.17.0.1


# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

security:
  authorization: enabled
  keyFile: /var/lib/mongodb/keys/mongo-keyfile

setParameter:
   logicalSessionRefreshMillis: 900000
   localLogicalSessionTimeoutMinutes: 45

#operationProfiling:

#replication:
replication:
  oplogSizeMB: 20480
  replSetName: rs0

#sharding:

## Enterprise-Only Options:

#auditLog:
