import { ALLOWED_BOARD_COLORS, ALLOWED_COLORS } from '/config/const';

const LABEL_COLORS = [...ALLOWED_COLORS];
const LIST_COLORS = [...ALLOWED_COLORS];
const CARD_COLORS = [...ALLOWED_COLORS];
const SWIMLANE_COLORS = [...ALLOWED_COLORS];
const BOARD_COLORS = [...ALLOWED_BOARD_COLORS];

export {
  BOARD_COLORS,
  CARD_COLORS,
  LABEL_COLORS,
  LIST_COLORS,
  SWIMLANE_COLORS,
};

