Package.describe({
  name: "wekan-bootstrap-datepicker",
  git: "https://github.com/uxsolutions/bootstrap-datepicker.git",
  summary: "A datepicker for twitter bootstrap (@twbs)",
  version: "1.10.0",
  documentation: 'README.md'
});

Package.onUse(function (api) {
  api.use('jquery', 'client');

  api.addFiles('bootstrap-datepicker/dist/js/bootstrap-datepicker.js', 'client');
  api.addFiles('bootstrap-datepicker/dist/css/bootstrap-datepicker3.css', 'client');
  api.addFiles([
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ar.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ar-tn.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.az.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bg.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bn.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.br.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bs.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ca.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.cs.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.cy.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.da.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.de.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.el.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-AU.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-CA.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-GB.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-IE.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-NZ.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-US.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-ZA.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.eo.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.es.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.et.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.eu.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fa.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fi.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fo.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fr.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fr-CH.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.gl.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.he.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hi.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hr.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hu.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hy.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.id.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.is.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.it.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.it-CH.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ja.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ka.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.kk.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.km.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ko.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.lv.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.me.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.mk.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.mn.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ms.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.nl.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.nl-BE.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.no.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.oc.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pl.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt-BR.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ro.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ru.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sk.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sl.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sq.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sr.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sr-latin.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sv.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ta.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.tg.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.th.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.tr.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uk.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uz-cyrl.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uz-latn.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.vi.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js',
    'bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-TW.min.js'
  ], 'client')
});
