'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const service = read('server/lib/legacyHtml4AttachmentResponse.js');
const route = read('server/legacyHtml4.js');
const page = read('server/lib/legacyHtml4Pages.js');

assert.match(service, /inlineMedia && !kind\.isAudio && !kind\.isVideo/);
assert.match(service, /safeDisposition\(inlineMedia \? 'inline' : 'attachment'/);
assert.match(service, /fileResponsePolicy\(attachment\.type, !inlineMedia\)/);
assert.match(service, /exactAuthorizedAttachment/);
assert.match(route, /preview-attachment-media/);
assert.match(route, /download:media-/);
assert.match(route, /\? 'media' : 'original'/);
assert.match(page, /kind\.isAudio \|\| kind\.isVideo/);
assert.match(page, /authPurpose: `download:media-/);
console.log('legacyHtml4MediaPreview: scoped inline audio/video response passed');
