'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');const read=c=>JSON.parse(fs.readFileSync(path.join(root,`imports/i18n/data/${c}.i18n.json`),'utf8'));const tig=read('tig'),ti=read('ti');const terms={
  "accept": "ቀብል",
  "attachment-limits": "ሕዱዳት",
  "color-silver": "ፍደት",
  "color-yellow": "ቢጫይ",
  "invite": "ዐዝም",
  "poker-finish": "አትመም",
  "upload": "ጸዐን",
  "voting": "ሕርያን",
  "worker": "ሸቃላይ",
  "board-view-control-chart": "ሕክም",
  "cleanup": "ከስተሮት",
  "minutes": "ደቃይቅ",
  "reports": "ጽበጣት",
  "request": "ሱአል",
  "requests": "ሱአላት",
  "computer": "ኮምፒተር",
  "features-security": "አምን",
  "event-attempts": "ጀርቤታት",
  "previous": "ቀዳሚት",
  "problems": "መሻክል",
  "progress": "ዐቦት",
  "schedule": "ጀድወል"
};for(const[k,v]of Object.entries(terms)){assert.equal(tig[k],v,`${k}: corpus-backed Tigre operation term`);assert.notEqual(tig[k],ti[k],`${k}: reject Tigrinya seed`)}console.log(`Checked ${Object.keys(terms).length} Tigre operational terms.`);
