'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');const read=c=>JSON.parse(fs.readFileSync(path.join(root,`imports/i18n/data/${c}.i18n.json`),'utf8'));const tig=read('tig'),ti=read('ti');const terms={
  "r-unit-days": "ምዕል(አምዕል)",
  "r-unit-hours": "ሰዐት(ሰዐታት)",
  "r-unit-weeks": "እስቡዕ(እስቡዓት)",
  "r-unit-months": "ወርሕ(አወርሕት)",
  "r-unit-minutes": "ደቂቀት(ደቃይቅ)",
  "card-id": "መለለዪ ወረቀት ካርድ",
  "board-id": "መለለዪ ምዱድ",
  "job-name": "ስሜት ሹቁል",
  "create-task": "ሹቁል ኽለቅ",
  "text-color": "ሕብር ክቱብ",
  "total-size": "ጅሙዕ ቅያስ",
  "due-date": "አምዐል መዋዕድ",
  "gantt-view-half-day": "ፍርቂ ምዕል",
  "filter-no-label": "እሻረት የለን",
  "myCardsSortChange-choice-board": "እብ ምዱድ",
  "all-boards": "ክሎም ምዱዳት",
  "close-card": "ወረቀት ካርድ ድባእ",
  "close-board": "ምዱድ ድባእ",
  "copyCardPopup-title": "ወረቀት ካርድ ነቅል",
  "copyListPopup-title": "ዝርዝር ነቅል",
  "sort-cards": "ወረቀት ካርዳት ስርዓም",
  "cardsSortPopup-title": "ወረቀት ካርዳት ስርዓም",
  "listsortPopup-title": "ዝርዝር ስርዓም",
  "r-list-name": "ስሜት ዝርዝር",
  "r-in-list": "እት ዝርዝር",
  "this-card": "እሊ ወረቀት ካርድ",
  "r-the-board": "ለምዱድ"
};for(const[k,v]of Object.entries(terms)){assert.equal(tig[k],v,`${k}: coordinated Tigre compound`);assert.notEqual(tig[k],ti[k],`${k}: reject Tigrinya seed`)}for(const k of ['r-unit-days','r-unit-hours','r-unit-weeks','r-unit-months','r-unit-minutes'])assert.match(tig[k],/^.+\(.+\)$/);console.log(`Checked ${Object.keys(terms).length} Tigre compounds.`);
