'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=code=>JSON.parse(fs.readFileSync(path.join(root,`imports/i18n/data/${code}.i18n.json`),'utf8'));
const veps=read('ve-PP');
const finnish=read('fi');
const terms={
  "prefix-with-full-path": "Liža täuz’ te ezmaižehe",
  "prefix-with-parent": "Liža vanhemb ezmaižehe",
  "subtext-with-full-path": "Liža täuz’ te alatekstaks",
  "subtext-with-parent": "Liža vanhemb alatekstaks",
  "add-custom-html-after-body-start": "Ližada ičemäne HTML <body>-tagan jäl’ghe",
  "add-custom-html-before-body-end": "Ližada ičemäne HTML </body>-tagan edele",
  "addmore-detail": "Ližada tarkemb kuvadand",
  "myCardsViewChange-title": "Minun kartoiden nägo",
  "myCardsViewChangePopup-title": "Minun kartoiden nägo",
  "myCardsViewChange-choice-boards": "Laudad",
  "myCardsViewChange-choice-table": "Tablic",
  "myCardsSortChange-title": "Minun kartoiden järgenduz",
  "myCardsSortChangePopup-title": "Minun kartoiden järgenduz",
  "myCardsSortChange-choice-board": "Laudan mödhe",
  "broken-cards": "Rikotud kartad",
  "list-title-not-found": "Lugetiž '%s' ei ole löutud.",
  "team-name-not-found": "Jouk '%s' ei ole löutud.",
  "globalSearch-title": "Ectä kaikiš laudoiš",
  "no-cards-found": "Kartoid ei ole löutud.",
  "one-card-found": "Üks’ kart om löutud",
  "n-cards-found": "%s kartad om löutud",
  "n-n-of-n-cards-found": "__start__–__end__ / __total__ kartad om löutud",
  "operator-customfield": "ičemänepöud",
  "operator-attachment-text": "tartutadudfail",
  "operator-checklist-text": "kodvindlugetiž",
  "predicate-archived": "arhivas",
  "predicate-open": "avaidud",
  "predicate-selector": "valičii",
  "predicate-projection": "projekcii",
  "heading-notes": "Homaičused",
  "globalSearch-instructions-heading": "Ecindan opastused",
  "globalSearch-instructions-operator-hash": "`__operator_label_abbrev__<name|color>` — lühüd muod `__operator_label__:<color>` libo `__operator_label__:<name>`",
  "globalSearch-instructions-status-archived": "`__predicate_archived__` — arhivas olevad kartad",
  "link-to-search": "Link necile ecindale",
  "label-colors": "Znamoiden mujud",
  "sort-cards": "Järgenda kartad",
  "sort-is-on": "Järgenduz om päl",
  "cardsSortPopup-title": "Järgenda kartad",
  "created-at-newest-first": "Tehtud (uzimad ezmäi)",
  "created-at-oldest-first": "Tehtud (vanhembad ezmäi)",
  "links-heading": "Linkad",
  "move-swimlane": "Sirdä ujundšoid",
  "moveSwimlanePopup-title": "Sirdä ujundšoid",
  "filesReportTitle": "Failoiden raport",
  "reports": "Raportad",
  "rulesReportTitle": "Praviloiden raport",
  "boardsReportTitle": "Laudoiden raport",
  "cardsReportTitle": "Kartoiden raport",
  "impersonation-admin": "Administrator",
  "copy-swimlane": "Kopirui ujundšoid",
  "copySwimlanePopup-title": "Kopirui ujundšoid",
  "display-card-creator": "Ozuta kartan tegii",
  "maximize-card": "Suurenda kart",
  "minimize-card": "Pičenda kart",
  "carbon-copy": "Kopii (Cc:)",
  "ticket": "Bilet",
  "tickets": "Biletad",
  "ticket-number": "Biletan numer",
  "open": "Avaidud",
  "pending": "Odotab",
  "closed": "Saubatud",
  "resolved": "Ratkaistud",
  "cancelled": "Heittud",
  "request": "Pakičend",
  "requests": "Pakičendad",
  "help-request": "Abun pakičend",
  "editCardSortOrderPopup-title": "Vajehta järgenduz",
  "cardDetailsPopup-title": "Kartan ližatedod",
  "filter-card-title-label": "Puhtasta kartan pälkirjutezen mödhe",
  "copied": "Kopiruidud!",
  "moveChecklist": "Sirdä kodvindlugetiž",
  "moveChecklistPopup-title": "Sirdä kodvindlugetiž",
  "originOrder": "alguiž järgenduz",
  "copyChecklist": "Kopirui kodvindlugetiž",
  "copyChecklistPopup-title": "Kopirui kodvindlugetiž",
  "card-show-lists": "Ozuta lugetižed kartal",
  "attachmentActionsPopup-title": "Ličtusen tegendad",
  "attachment-move-storage-s3": "Sirdä ličtuz S3-ha",
  "attachment-move": "Sirdä ličtuz",
  "move-progress-pause": "Seizata",
  "move-progress-resume": "Jatkta",
  "stats-scope": "Tip",
  "board-id": "Laudan ID",
  "path": "Te",
  "version-name": "Versijan nimi",
  "storage": "Kaicend",
  "remaining_time": "Jäližjäänud aig",
  "speed": "Radviduz",
  "progress": "Edenduz",
  "if-you-already-have-an-account": "Ku sinun akkaunt jo om",
  "register": "Registriruida",
  "minicardDetailsActionsPopup-title": "Kartan ližatedod",
  "Mongo_sessions_count": "Mongo-seansiden lugumär",
  "translation": "Kändand",
  "translation-text": "Kändadud tekst",
  "convert-to-markdown": "Muuta Markdownaks",
  "uncollapse": "Levita",
  "support-page-enabled": "Abun lehtpol’ om päl",
  "support-title": "Abun pälkirjutez",
  "support-content": "Abun südäimuz",
  "board-operations": "Laudan tegendad",
  "cron-migrations": "Plänitud sirdändad",
  "cron-error-severity": "Väran jügeduz",
  "cron-error-message": "Väran tedotuz",
  "cron-clear-errors": "Heitä kaik värad",
  "complete": "Val’miž",
  "idle": "Joudai",
  "sandstorm-storage-item": "Kaicend",
  "features-notifications": "Tedotuzed",
  "backup-restore": "Pöruta",
  "gridfs-enabled": "GridFS om päl",
  "all-migrations": "Kaik sirdändad",
  "select-migration": "Valiče sirdänd",
  "start": "Augota",
  "pause": "Seizata",
  "migration-progress": "Sirdändan edenduz",
  "add-job": "Ližada tegomäär",
  "attachment-migration": "Ličtusiden sirdänd",
  "attachment-settings": "Ličtusiden sändod",
  "attachment-storage-settings": "Kaicendan sändod",
  "automatic-migration": "Avtomatine sirdänd",
  "migration-progress-title": "Laudan sirdänd om teges",
  "migration-progress-overall": "Ühtine edenduz",
  "migration-progress-current-step": "Nügüdläine askel",
  "has-swimlanes": "Om ujundšoiduid",
  "step-fix-orphaned-cards": "Kohenda ižandatomad kartad",
  "step-convert-shared-lists": "Muuta jagetud lugetižed",
  "step-create-missing-lists": "Tege puudujad lugetižed",
  "step-fix-missing-ids": "Kohenda puudujad ID-d",
  "completed": "Loptud",
  "converting-board": "Laudad muudetase",
  "cpu-cores": "CPU-jurad",
  "current-action": "Nügüdläine tegenda",
  "days-old": "Päiväd vanha",
  "filesystem-storage": "Failsisteman kaicend",
  "force-board-scan": "Pakita laudan skanirind",
  "gridfs-attachments": "GridFS-ličtused",
  "gridfs-size": "GridFS-suruz’",
  "idle-migration": "Joudai sirdänd",
  "job-description": "Tegomääran kuvadand",
  "job-details": "Tegomääran ližatedod",
  "job-name": "Tegomääran nimi",
  "job-queue": "Tegomääriden jono",
  "last-run": "Jäl’gmäine käivituz",
  "max-concurrent": "Enin ühtaigad",
  "migrate-all-to-gridfs": "Sirdä kaik GridFS-ha",
  "migrate-all-to-s3": "Sirdä kaik S3-ha",
  "migrated-attachments": "Sirttud ličtused",
  "migration-detector": "Sirdändan löudai",
  "next-run": "Tuleb käivituz",
  "overall-progress": "Ühtine edenduz",
  "remaining-attachments": "Jäližjäänud ličtused",
  "run-once": "Käivitada üks’ kerad",
  "s3-attachments": "S3-ličtused",
  "s3-size": "S3-suruz’",
  "scanning-status": "Skanirindan status",
  "schedule": "Aigplän",
  "show-list-on-minicard": "Ozuta lugetiž minikartal",
  "showing": "Ozutadas",
  "start-test-operation": "Augota test-tegenda",
  "start-time": "Augotižaig",
  "step-progress": "Askelen edenduz",
  "system-resources": "Sisteman resursad",
  "total-attachments": "Ličtused kaiked",
  "total-operations": "Tegendad kaiked",
  "total-size": "Ühtine suruz’",
  "unmigrated-boards": "Sirdmatoi laudad",
  "cron": "Cron",
  "current-step": "Nügüdläine askel",
  "otp": "OTP-kod",
  "size-bytes": "Suruz’ (baitad)",
  "last-modified": "Jäl’gmäižikš vajehtadud",
  "api-endpoints": "API-loppukohdad",
  "otp-required": "OTP-kod om tarbiž",
  "user-exists": "Kävutai jo om olemas",
  "log": "Žurnal",
  "protocol": "Protokol"
};
for(const [key,value] of Object.entries(terms)){
 assert.equal(veps[key],value,`${key}: exact reviewed Veps value`);
 assert.notEqual(veps[key],finnish[key],`${key}: Finnish seed removed`);
}
console.log(`vepsFinalFamilies: ${Object.keys(terms).length} terms passed`);
