'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = code => JSON.parse(fs.readFileSync(path.join(root, `imports/i18n/data/${code}.i18n.json`), 'utf8'));
const veps = read('ve-PP');
const finnish = read('fi');
const terms = {
  "activities": "Tegendad",
  "add-attachment": "Ližada tartutadud fail",
  "add-board": "Ližada laud",
  "add-card": "Ližada kart",
  "addListPopup-title": "Ližada lugetiž",
  "add-list": "Ližada lugetiž",
  "add-after-list": "Ližada lugetižen jäl'ghe",
  "add-swimlane": "Ližada ujundšoid",
  "add-members": "Ližada ühtnikad",
  "addMemberPopup-title": "Ližada ühtnikad",
  "memberPopup-title": "Ühtnikan valičused",
  "apply": "Kävuta",
  "restore-board": "Endišta laud",
  "no-archived-boards": "Arhivas ei ole laudoid.",
  "attachmentDeletePopup-title": "Heitä tartutadud fail?",
  "board-change-color": "Vajehta muju",
  "board-change-background-image": "Vajehta tagakuva",
  "add-background-image": "Ližada tagakuva",
  "remove-background-image": "Heitä tagakuva",
  "board-info-on-my-boards": "Kaikiden laudoiden valičused",
  "boardInfoOnMyBoardsPopup-title": "Kaikiden laudoiden valičused",
  "boardInfoOnMyBoards-title": "Kaikiden laudoiden valičused",
  "board_members": "Kaik laudan ühtnikad",
  "board-not-found": "Laud ei ole löutud",
  "boardChangeColorPopup-title": "Vajehta laudan tagakuva",
  "boardChangeBackgroundImagePopup-title": "Vajehta tagakuva",
  "allBoardsChangeColorPopup-title": "Vajehta muju",
  "allBoardsChangeBackgroundImagePopup-title": "Vajehta tagakuva",
  "boardChangeTitlePopup-title": "Anda laudale uz’ nimi",
  "boardChangeWatchPopup-title": "Vajehta kaceluz",
  "boardChangeViewPopup-title": "Laudan nägo",
  "boards": "Laudad",
  "calendar-previous-month-label": "Edeline ku",
  "calendar-next-month-label": "Uz’ ku",
  "listArchivePopup-title": "Sirdä lugetiž arhivaha?",
  "swimlaneArchivePopup-title": "Sirdä ujundšoid arhivaha?",
  "card-spent": "Kävutadud aig",
  "card-edit-attachments": "Vajehta tartutadud failoid",
  "card-edit-labels": "Vajehta znamoid",
  "card-edit-members": "Vajehta ühtnikoid",
  "cardAttachmentsPopup-title": "Ližada fail",
  "cardCustomField-datePopup-title": "Vajehta päivmär",
  "set-estimation": "Pane arvoi",
  "cardDeletePopup-title": "Heitä kart?",
  "cardArchivePopup-title": "Sirdä kart arhivaha?",
  "cardDetailsActionsPopup-title": "Kartan tegendad",
  "cardAssigneePopup-title": "Märitud kävutai",
  "cardLabelsPopup-title": "Znamad",
  "cardMembersPopup-title": "Ühtnikad",
  "cardTemplatePopup-title": "Tege vilitez",
  "cards-count": "Kartad",
  "cards-count-one": "Kart",
  "cardType-card": "Kart",
  "cardType-linkedCard": "Sidotud kart",
  "cardType-linkedBoard": "Sidotud laud",
  "change-permissions": "Vajehta oigused",
  "change-settings": "Vajehta valičused",
  "text-note-text": "Tekst",
  "changeLanguagePopup-title": "Vajehta kel’",
  "changePermissionsPopup-title": "Vajehta oigused",
  "changeSettingsPopup-title": "Vajehta valičused",
  "close-card": "Saubata kart",
  "deleteCommentPopup-title": "Heitä sel’genzoituz?",
  "linkCardPopup-title": "Sido kart",
  "copyCardPopup-title": "Kopirui kart",
  "copyListPopup-title": "Kopirui lugetiž",
  "createBoardPopup-title": "Tege laud",
  "chooseBoardSourcePopup-title": "To laud",
  "createLabelPopup-title": "Tege znam",
  "createCustomField": "Tege pöud",
  "createCustomFieldPopup-title": "Tege pöud",
  "deleteLabelPopup-title": "Heitä znam?",
  "editCustomFieldPopup-title": "Vajehta pöud",
  "addReactionPopup-title": "Ližada reakcii",
  "editLabelPopup-title": "Vajehta znam",
  "export-card": "Ve kart",
  "export-card-pdf": "Ve kart PDF-failaha",
  "export-card-excel": "Ve kart Excel-failaha",
  "exportBoardPopup-title": "Ve laud",
  "exportCardPopup-title": "Ve kart",
  "sorted": "Järgendatud",
  "remove-sort": "Heitä järgenduz",
  "list-sort-by": "Järgenda lugetiž:",
  "filter-clear": "Heitä puhtastim",
  "filter-show-archive": "Ozuta arhiv-azjad",
  "filter-on": "Puhtastim om päl",
  "show-activities": "Ozuta tegendad",
  "headerBarCreateBoardPopup-title": "Tege laud",
  "import-board": "to laud",
  "import-board-c": "To laud",
  "label-create": "Tege znam",
  "link-card": "Link necile kartale",
  "linkCardToBoardPopup-title": "Link laudale",
  "set-color-list": "Pane muju",
  "listActionPopup-title": "Lugetižen tegendad",
  "swimlaneActionPopup-title": "Ujundšoidun tegendad",
  "swimlaneAddPopup-title": "Ližada ujundšoid alaha",
  "link-list": "Link necile lugetišele",
  "swimlanes": "Ujundšoidud",
  "memberMenuPopup-title": "Ühtnikan valičused",
  "move-selection": "Sirdä valičuz",
  "copy-selection": "Kopirui valičuz",
  "moveCardPopup-title": "Sirdä kart",
  "moveListPopup-title": "Sirdä lugetiž",
  "moveCardToBottom-title": "Sirdä lophu",
  "moveCardToTop-title": "Sirdä augotišehe",
  "moveSelectionPopup-title": "Sirdä valičuz",
  "copySelectionPopup-title": "Kopirui valičuz",
  "selection-color": "Valičuzan muju",
  "my-boards": "Minun laudad",
  "no-archived-cards": "Arhivas ei ole kartoid.",
  "no-archived-lists": "Arhivas ei ole lugetižid.",
  "remove-from-board": "Heitä laudaspäi",
  "listDeletePopup-title": "Heitä lugetiž?",
  "remove-member": "Heitä ühtnik",
  "remove-member-from-card": "Heitä kartaspäi",
  "removeMemberPopup-title": "Heitä ühtnik?",
  "rename-board": "Anda laudale uz’ nimi",
  "select-color": "Valiče muju",
  "select-board": "Valiče laud",
  "starred-boards": "Tähtaižed laudad",
  "this-board": "nece laud",
  "this-card": "nece kart",
  "view-it": "Kacu sidä",
  "go-to-board": "Mäne laudale",
  "admin-panel": "Administratoran panel’",
  "invite": "Kucu",
  "invite-people": "Kucu ristitud"
};
for (const [key, value] of Object.entries(terms)) {
  assert.equal(veps[key], value, `${key}: exact reviewed Veps UI composition`);
  assert.notEqual(veps[key], finnish[key], `${key}: Finnish seed removed`);
}
console.log(`vepsUiFamilies: ${Object.keys(terms).length} terms passed`);
