'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=code=>JSON.parse(fs.readFileSync(path.join(root,`imports/i18n/data/${code}.i18n.json`),'utf8'));
const veps=read('ve-PP');
const finnish=read('fi');
const terms={
  "accept": "Ota",
  "allboards.starred": "Tähtaižed",
  "allboards.remaining": "Jäliž",
  "setSwimlaneHeightPopup-title": "Pane ujundšoidun korktuz’",
  "set-swimlane-height": "Pane ujundšoidun korktuz’",
  "convertChecklistItemToCardPopup-title": "Tege kartaks",
  "and-n-other-card": "Da __count__ toiž kart",
  "and-n-other-card_plural": "Da __count__ toižta kartad",
  "attached": "Tartutadud",
  "board-background-image-url": "Tagakuvan URL",
  "board-nb-stars": "%s tähtast",
  "adminChangeAvatarPopup-title": "Vajehta kävutajan kuva",
  "casSignIn": "Tule sistemaha CAS:n abul",
  "samlSignIn": "Tule sistemaha SAML:n abul",
  "changeAvatarPopup-title": "Vajehta kävutajan kuva",
  "deleteAvatarPopup-title": "Heitä kävutajan kuva?",
  "color-crimson": "veripunai",
  "color-darkgreen": "pimed vihand",
  "color-indigo": "indigon muju",
  "color-mistyrose": "kelme ruza",
  "color-navy": "pimed sinine",
  "color-paleturquoise": "kelme turkuaz",
  "color-peachpuff": "persikan muju",
  "color-plum": "slivan muju",
  "color-purple": "purpur",
  "color-saddlebrown": "satulan bur",
  "color-slateblue": "slate-sinine",
  "unset-color": "Heitä valičuz",
  "worker": "Tegii",
  "createTemplateContainerPopup-title": "Ližada vilitez-konteiner",
  "custom-field-currency": "Valüt",
  "custom-field-currency-option": "Valütan kod",
  "date-format": "Päivmäran format",
  "decline": "Hül’gäta",
  "default-avatar": "Sanumata kävutajan kuva",
  "edit-profile": "Vajehta profili",
  "editCardSpentTimePopup-title": "Vajehta kävutadud aig",
  "editNotificationPopup-title": "Vajehta tedotuz",
  "editProfilePopup-title": "Vajehta profili",
  "email-invite-subject": "__inviter__ kutsub sindai",
  "push-invite-title": "__inviter__ kutsub sindai",
  "export-ical-feed": "Kalendar'-virduz (iCal)",
  "export-card-attachment-type": "Tip",
  "export-card-attachment-uploaded-by": "Ladinai",
  "export-card-attachment-uploaded-at": "Ladind aig",
  "export-card-attachment-image-previews": "Kuvien ezikacundad",
  "export-card-excel-free": "joudai",
  "export-card-excel-needed": "tarbiž",
  "list-label-modifiedAt": "Jäl’gmäine pästandaig",
  "list-label-title": "Lugetižen nimi",
  "filter-to-selection": "Puhtasta valičuzha",
  "fullname": "Täuz’ nimi",
  "header-logo-title": "Pörte laudoiden lehtpolele.",
  "impersonate-user": "Tegoiže kut toiž kävutai",
  "import-map-members": "Ühtenzoita ühtnikad",
  "importMapMembersAddPopup-title": "Valiče ühtnik",
  "initials": "Algkirjamed",
  "joined": "ühtnui",
  "label-default": "%s znam (sanumata)",
  "settingsUserPopup-title": "Kävutajan valičused",
  "settingsTeamPopup-title": "Joukun valičused",
  "settingsOrgPopup-title": "Organizacijan valičused",
  "listImportCardPopup-title": "To Trello-kart",
  "listImportCardsTsvPopup-title": "To Excel CSV/TSV",
  "muted": "Vaigendanuded",
  "page-not-found": "Lehtpol’ ei ole löutud.",
  "participating": "Ozanottai",
  "profile": "Profil",
  "signupPopup-title": "Tege akkaunt",
  "subscribe": "Tilata",
  "overtime-hours": "Ližatö (časud)",
  "overtime": "Ližatö",
  "pomodoro": "Pomodoro-aig",
  "has-overtime-cards": "Om ližatö-kartoid",
  "tracking": "Kaceluz",
  "import-usernames": "To kävutajiden nimed",
  "welcome-board": "Tervhtulendan laud",
  "welcome-swimlane": "Verst 1",
  "welcome-list1": "Pohjad",
  "registration": "Registracii",
  "to-boards": "Laudoile",
  "send-from": "Kenespäi",
  "email-templates-title": "Email-vilitezad",
  "email-templates-invite-subject": "Kucundan emailan azj",
  "email-templates-invite-body": "Kucundan emailan tekst",
  "email-templates-activity-subject": "Tegendan tedotusen emailan azj",
  "email-invite-register-subject": "__inviter__ kutsub sindai",
  "outgoingWebhooksPopup-title": "Lähtejad webhukad",
  "boardCardTitlePopup-title": "Kartan pälkirjutezen puhtastim",
  "no-name": "(Tundmatoi)",
  "Node_version": "Node-versii",
  "Meteor_version": "Meteor-versii",
  "MongoDB_Oplog_enabled": "MongoDB Oplog om päl",
  "tableVisibilityMode": "Laudoiden nägubuz",
  "createdAt": "Tehtud",
  "modifiedAt": "Vajehtadud",
  "verified": "Tarkštatud",
  "active-team": "Aktivine jouk",
  "active-org": "Aktivine organizacii",
  "active-person": "Aktivine ristitud",
  "setCardColorPopup-title": "Pane muju",
  "setSelectionColorPopup-title": "Pane valičuzan muju",
  "setCardActionsColorPopup-title": "Valiče muju",
  "setSwimlaneColorPopup-title": "Valiče muju",
  "setListColorPopup-title": "Valiče muju",
  "assigned-by": "Märii",
  "requested-by": "Pakičii",
  "boardDeletePopup-title": "Heitä laud?",
  "delete-board": "Heitä laud",
  "card-settings": "Kartan sändod",
  "minicard-settings": "Minikartan sändod",
  "boardSubtaskSettingsPopup-title": "Alategendoiden sändod",
  "boardCardSettingsPopup-title": "Kartan sändod",
  "boardMinicardSettingsPopup-title": "Minikartan sändod",
  "description-on-minicard": "Kuvadand minikartal",
  "source-board": "Lähtelaud",
  "r-add-trigger": "Ližada käivitai",
  "r-board-rules": "Laudan pravilad",
  "r-view-rule": "Kacu pravil",
  "r-new-rule-name": "Uden pravilan pälkirjutez",
  "r-no-rules": "Praviloid ei ole",
  "r-trigger": "Käivitai",
  "set-filter": "Pane puhtastim",
  "r-top-of": "Augotiš",
  "r-bottom-of": "Lop",
  "r-set-color": "Pane mujuks",
  "r-to": "kenele",
  "r-rule-details": "Pravilan ližatedod",
  "r-d-send-email-to": "kenele",
  "r-in-swimlane": "ujundšoidul",
  "r-by": "aighasai",
  "r-swimlane-name": "ujundšoidun nimi",
  "r-set": "Pane",
  "r-update": "Udišta",
  "r-datefield": "päivmär-pöud",
  "r-df-start-at": "augotiž",
  "r-to-current-datetime": "nügüdläižele päevmärele/aigale",
  "r-remove-value-from": "Heitä znamoičend",
  "r-link-card": "Sido kart",
  "authentication-method": "Autentifikacijan metod",
  "authentication-type": "Autentifikacijan tip",
  "custom-product-name": "Ičemäne produktan nimi",
  "layout": "Asetuz",
  "hide-logo": "Peitä logo",
  "display-authentication-method": "Ozuta autentifikacijan metod",
  "default-authentication-method": "Sanumata autentifikacijan metod",
  "people-number": "Ristituden lugumär om:",
  "swimlaneDeletePopup-title": "Heitä ujundšoid?",
  "restore-all": "Endišta kaik",
  "previous_as": "edeline oli",
  "no-assignee": "Märitud kävutajad ei ole",
  "no-label": "Znamad ei ole",
  "cardAssigneesPopup-title": "Märitud kävutai",
  "editOrgPopup-title": "Vajehta organizacii",
  "editTeamPopup-title": "Vajehta jouk",
  "editUserPopup-title": "Vajehta kävutai",
  "newUserPopup-title": "Uz’ kävutai",
  "last-modified-at": "Jäl’gmäižikš vajehtadud",
  "last-activity": "Jäl’gmäine tegenda",
  "create-task": "Tege tegomäär",
  "displayName": "Nägub nimi",
  "shortName": "Lühüd nimi",
  "website": "Web-lehtpol’",
  "person": "Ristitud",
  "my-cards": "Minun kartad"
};
for(const [key,value] of Object.entries(terms)){
 assert.equal(veps[key],value,`${key}: exact reviewed Veps value`);
 assert.notEqual(veps[key],finnish[key],`${key}: Finnish seed removed`);
}
console.log(`vepsStatusFamilies: ${Object.keys(terms).length} terms passed`);
