name: 🛡️ Security Issue
description: Report a security vulnerability
labels: ["security", "critical"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT: Please do not report security vulnerabilities via public issues.
        
        To protect the Wekan community, we ask that you report security bugs privately. This allows us to fix the issue before it can be exploited by malicious actors.
        
        ### How to report:
        Please read our **[Security Policy (SECURITY.md)](https://github.com/wekan/wekan/blob/main/SECURITY.md)** for the official reporting process and contact information.

