      # ========== CUSTOM END =====
      ## See ../multitenancy.md about commented out settings:
      - METEOR_REACTIVITY_ORDER=changeStreams,oplog,polling
      - DDP_TRANSPORT=uws
      #- METEOR_REACTIVITY_ORDER=oplog,polling
      #- DDP_TRANSPORT=sockjs
      - WRITABLE_PATH=/data
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - NODE_FLAGS=--max-old-space-size=16384
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-files:/data:rw

volumes:
  wekan-files:
    driver: local
