const GLOBAL_SEARCH_HELP_TAGS = Object.freeze({
  operator_board: 'operator-board', operator_list: 'operator-list',
  operator_swimlane: 'operator-swimlane', operator_comment: 'operator-comment',
  operator_label: 'operator-label', operator_label_abbrev: 'operator-label-abbrev',
  operator_user: 'operator-user', operator_user_abbrev: 'operator-user-abbrev',
  operator_member: 'operator-member', operator_member_abbrev: 'operator-member-abbrev',
  operator_assignee: 'operator-assignee', operator_assignee_abbrev: 'operator-assignee-abbrev',
  operator_creator: 'operator-creator', operator_due: 'operator-due',
  operator_created: 'operator-created', operator_modified: 'operator-modified',
  operator_status: 'operator-status', operator_has: 'operator-has',
  operator_sort: 'operator-sort', operator_limit: 'operator-limit',
  operator_debug: 'operator-debug', operator_org: 'operator-org',
  operator_team: 'operator-team', operator_number: 'operator-number',
  predicate_overdue: 'predicate-overdue', predicate_archived: 'predicate-archived',
  predicate_all: 'predicate-all', predicate_ended: 'predicate-ended',
  predicate_week: 'predicate-week', predicate_month: 'predicate-month',
  predicate_quarter: 'predicate-quarter', predicate_year: 'predicate-year',
  predicate_attachment: 'predicate-attachment', predicate_description: 'predicate-description',
  predicate_checklist: 'predicate-checklist', predicate_public: 'predicate-public',
  predicate_private: 'predicate-private', predicate_due: 'predicate-due',
  predicate_created: 'predicate-created', predicate_modified: 'predicate-modified',
  predicate_start: 'predicate-start', predicate_end: 'predicate-end',
  predicate_assignee: 'predicate-assignee', predicate_member: 'predicate-member',
  predicate_selector: 'predicate-selector', predicate_projection: 'predicate-projection',
});

const GLOBAL_SEARCH_HELP_LINES = Object.freeze([
  ['# ', 'globalSearch-instructions-heading'],
  ['\n', 'globalSearch-instructions-description'],
  ['\n\n', 'globalSearch-instructions-operators'],
  ['\n- ', 'globalSearch-instructions-operator-board'],
  ['\n- ', 'globalSearch-instructions-operator-list'],
  ['\n- ', 'globalSearch-instructions-operator-swimlane'],
  ['\n- ', 'globalSearch-instructions-operator-comment'],
  ['\n- ', 'globalSearch-instructions-operator-label'],
  ['\n- ', 'globalSearch-instructions-operator-hash'],
  ['\n- ', 'globalSearch-instructions-operator-user'],
  ['\n- ', 'globalSearch-instructions-operator-at'],
  ['\n- ', 'globalSearch-instructions-operator-member'],
  ['\n- ', 'globalSearch-instructions-operator-assignee'],
  ['\n- ', 'globalSearch-instructions-operator-creator'],
  ['\n- ', 'globalSearch-instructions-operator-org'],
  ['\n- ', 'globalSearch-instructions-operator-team'],
  ['\n- ', 'globalSearch-instructions-operator-number'],
  ['\n- ', 'globalSearch-instructions-operator-due'],
  ['\n- ', 'globalSearch-instructions-operator-created'],
  ['\n- ', 'globalSearch-instructions-operator-modified'],
  ['\n- ', 'globalSearch-instructions-operator-status'],
  ['\n    - ', 'globalSearch-instructions-status-archived'],
  ['\n    - ', 'globalSearch-instructions-status-public'],
  ['\n    - ', 'globalSearch-instructions-status-private'],
  ['\n    - ', 'globalSearch-instructions-status-all'],
  ['\n    - ', 'globalSearch-instructions-status-ended'],
  ['\n- ', 'globalSearch-instructions-operator-has'],
  ['\n- ', 'globalSearch-instructions-operator-sort'],
  ['\n- ', 'globalSearch-instructions-operator-limit'],
  ['\n## ', 'heading-notes'],
  ['\n- ', 'globalSearch-instructions-notes-1'],
  ['\n- ', 'globalSearch-instructions-notes-2'],
  ['\n- ', 'globalSearch-instructions-notes-3'],
  ['\n- ', 'globalSearch-instructions-notes-3-2'],
  ['\n- ', 'globalSearch-instructions-notes-4'],
  ['\n- ', 'globalSearch-instructions-notes-5'],
]);

module.exports = { GLOBAL_SEARCH_HELP_LINES, GLOBAL_SEARCH_HELP_TAGS };
