#!/usr/bin/env bash
# Snapcraft hashes every file in its project directory, including .git. Keep
# mutable Git metadata outside that directory so --recover finds the same recipe.
set -euo pipefail
arch=${1:?Usage: prepare-launchpad-source.sh <architecture>}
case "$arch" in armhf|ppc64el|s390x|riscv64) ;; *) echo "Unsupported Launchpad architecture: $arch" >&2; exit 2 ;; esac
root=$(git rev-parse --show-toplevel)
source_dir="$root/.tools/tmp/snap-launchpad-source"
git_dir="$root/.tools/tmp/snap-launchpad-git"
export TMPDIR="$root/.tools/tmp"
mkdir -p "$TMPDIR"
# These two task-owned directories are generated by this script only.
rm -rf "$source_dir" "$git_dir"
mkdir -p "$source_dir"
snapshot_date=$(git -C "$root" show -s --format=%cI HEAD)
git -C "$root" archive HEAD | tar -x -C "$source_dir"
# Architecture is part of the source hash, preventing matrix legs from replacing
# one another's Launchpad recipes. The YAML comment does not change the build.
printf '\n# Launchpad build architecture: %s\n' "$arch" >> "$source_dir/snapcraft.yaml"
git init -q --separate-git-dir "$git_dir" "$source_dir"
# Keep Git's absolute pointer: Snapcraft copies this tree into its cache
# before uploading. A relative pointer breaks in that copy. Hosted job reruns
# use the same GITHUB_WORKSPACE path, so the pointer is stable across reruns.
git -C "$source_dir" config user.name 'github-actions[bot]'
git -C "$source_dir" config user.email '41898282+github-actions[bot]@users.noreply.github.com'
git -C "$source_dir" add -A
GIT_AUTHOR_DATE="$snapshot_date" GIT_COMMITTER_DATE="$snapshot_date" \
  git -C "$source_dir" commit -q -m "Launchpad $arch source snapshot"
echo "Prepared $arch source; shallow: $(git -C "$source_dir" rev-parse --is-shallow-repository)"
