/**
 * meteor-jade-loader
 *
 * A Rspack/webpack loader that compiles Meteor .jade template files into
 * JavaScript that registers Blaze templates via the Meteor Package globals.
 *
 * Usage in rspack/webpack config:
 *   {
 *     test: /\.jade$/,
 *     use: [{ loader: 'meteor-jade-loader' }],
 *   }
 *
 * Output is JavaScript that uses the Meteor Package globals (Template, HTML,
 * Blaze, Spacebars) which must be available at runtime.
 */

'use strict';

var path = require('path');
var getCompiler = require('./lib/jade-compiler');

/**
 * Generate the JS code for a single template registration.
 */
function generateTemplateJS(name, renderFuncCode) {
  var nameLiteral = JSON.stringify(name);
  var templateDotNameLiteral = JSON.stringify('Template.' + name);

  return 'Template.__checkName(' + nameLiteral + ');\n' +
         'Template[' + nameLiteral + '] = new Template(' + templateDotNameLiteral + ', ' + renderFuncCode + ');\n';
}

/**
 * Generate the JS code for the body content.
 */
function generateBodyJS(renderFuncCode) {
  return 'Template.body.addContent(' + renderFuncCode + ');\n' +
         'Meteor.startup(Template.body.renderToDocument);\n';
}

/**
 * The webpack/rspack loader function.
 * Receives .jade source, returns JavaScript string.
 */
function meteorJadeLoader(source) {
  var compiler = getCompiler();
  var JadeCompiler = compiler.JadeCompiler;
  var SpacebarsCompiler = compiler.SpacebarsCompiler;
  var HTML = compiler.HTML;

  var resourcePath = this.resourcePath || '';
  var basename = path.basename(resourcePath);

  // Determine mode: .tpl.jade = template mode, .jade = file mode
  var isTemplateMode = basename.endsWith('.tpl.jade');
  var fileMode = !isTemplateMode;

  try {
    var result = JadeCompiler.parse(source, {
      filename: resourcePath,
      fileMode: fileMode,
    });

    var jsOutput = '';

    // Preamble: get Meteor globals
    jsOutput += '/* Generated by meteor-jade-loader from ' + basename + ' */\n';
    jsOutput += 'var Template = Package["templating-runtime"].Template;\n';
    jsOutput += 'var HTML = Package.htmljs.HTML;\n';
    jsOutput += 'var Blaze = Package.blaze.Blaze;\n';
    jsOutput += 'var Spacebars = Package.spacebars.Spacebars;\n';
    jsOutput += 'var Meteor = Package.meteor.Meteor;\n';
    jsOutput += '\n';

    if (fileMode) {
      // File mode: result has { head, body, bodyAttrs, templates }
      if (result.head !== null) {
        // Head content is raw HTML that should be inserted into <head>.
        // In Rspack context, we skip head injection as it's typically
        // handled by the HTML plugin or Meteor's boilerplate.
        var headHTML = HTML.toHTML(result.head);
        if (headHTML) {
          jsOutput += '// Head content (typically handled by Meteor boilerplate):\n';
          jsOutput += '// ' + headHTML.replace(/\n/g, '\n// ') + '\n\n';
        }
      }

      if (result.body !== null) {
        var bodyRenderCode = SpacebarsCompiler.codeGen(result.body, {
          isBody: true,
          sourceName: '<body>',
        });
        jsOutput += generateBodyJS(bodyRenderCode);
      }

      // Generate code for each template defined in the file
      var templateNames = Object.keys(result.templates);
      for (var i = 0; i < templateNames.length; i++) {
        var tplName = templateNames[i];
        var tplTree = result.templates[tplName];
        var renderFuncCode = SpacebarsCompiler.codeGen(tplTree, {
          isTemplate: true,
          sourceName: 'Template "' + tplName + '"',
        });
        jsOutput += generateTemplateJS(tplName, renderFuncCode);
      }
    } else {
      // Template mode (.tpl.jade): result is the compiled AST directly
      var templateName = path.basename(resourcePath, '.tpl.jade');

      if (templateName === 'head') {
        var headHTML = HTML.toHTML(result);
        if (headHTML) {
          jsOutput += '// Head content: ' + headHTML.replace(/\n/g, '\n// ') + '\n';
        }
      } else if (templateName === 'body') {
        var bodyRenderCode = SpacebarsCompiler.codeGen(result, {
          isBody: true,
          sourceName: '<body>',
        });
        jsOutput += generateBodyJS(bodyRenderCode);
      } else {
        var renderFuncCode = SpacebarsCompiler.codeGen(result, {
          isTemplate: true,
          sourceName: 'Template "' + templateName + '"',
        });
        jsOutput += generateTemplateJS(templateName, renderFuncCode);
      }
    }

    return jsOutput;

  } catch (err) {
    // Emit the error properly through webpack
    var error = new Error('Jade compilation error in ' + resourcePath + ': ' + err.message);
    error.stack = err.stack;
    this.emitError(error);
    // Return empty module to avoid build crash
    return '/* Jade compilation error: ' + err.message.replace(/\*\//g, '* /') + ' */\n';
  }
}

module.exports = meteorJadeLoader;
